### ISSUE TITLE
Windows Phone 8 never really discards NFC listener properly and re-assigning doesn't seem to work properly

### ISSUE THREAD

**Issue by JohnMcLear** [chariotsolutions/phonegap-nfc#115]
If I have a page..

My HTML files
Index.html
createAction.html

I browse to createAction.html, do ``addNdefListener``, write some tags then do a ``window.location = index.html`` then re-visit createAction.html the second time the addNdefListener fails..

Initialized the NfcPlugin is only output..

I think if there is a way I can check before I try to do addNdefListener if it's already been executed that would help..  Can you replicate this issue on WP by trying to add addNdefListener twice?

It's very probable my code is to blame here, it works fine on Android tho..

**Comment by don** [comment]
This works on windows platform. Tested with Lumia 640 running Windows Phone 8.1 Update 2.

Not planning on fixing Windows Phone 8 / SilverLight version.

@JohnMcLear if your still seeing a problem re-open with an updated example.
