### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by janhar** [chariotsolutions/phonegap-nfc#119]
Hi,

I receive the following exception when I run the plugin on Android 2.3.6:

D/CordovaLog( 1380): : Line 1203501237 : Received Event: deviceready
I/Web Console( 1380): Received Event: deviceready at :1203501237
W/dalvikvm( 1380): Link of class 'Lcom/chariotsolutions/nfc/plugin/NfcPlugin;' failed
W/System.err( 1380): java.lang.ClassNotFoundException: com.chariotsolutions.nfc.plugin.NfcPlugin
W/System.err( 1380):    at java.lang.Class.classForName(Native Method)
W/System.err( 1380):    at java.lang.Class.forName(Class.java:234)
W/System.err( 1380):    at java.lang.Class.forName(Class.java:181)
W/System.err( 1380):    at org.apache.cordova.PluginEntry.getClassByName(PluginEntry.java:117)
W/System.err( 1380):    at org.apache.cordova.PluginEntry.createPlugin(PluginEntry.java:93)
W/System.err( 1380):    at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:278)
W/System.err( 1380):    at org.apache.cordova.PluginManager.execHelper(PluginManager.java:232)
W/System.err( 1380):    at org.apache.cordova.PluginManager.exec(PluginManager.java:227)
W/System.err( 1380):    at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:53)
W/System.err( 1380):    at android.webkit.JWebCoreJavaBridge.sharedTimerFired(Native Method)
W/System.err( 1380):    at android.webkit.JWebCoreJavaBridge.sharedTimerFired(Native Method)
W/System.err( 1380):    at android.webkit.JWebCoreJavaBridge.fireSharedTimer(JWebCoreJavaBridge.java:91)
W/System.err( 1380):    at android.webkit.JWebCoreJavaBridge.handleMessage(JWebCoreJavaBridge.java:108)
W/System.err( 1380):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 1380):    at android.os.Looper.loop(Looper.java:130)
W/System.err( 1380):    at android.webkit.WebViewCore$WebCoreThread.run(WebViewCore.java:747)
W/System.err( 1380):    at java.lang.Thread.run(Thread.java:1019)
W/System.err( 1380): Caused by: java.lang.NoClassDefFoundError: com.chariotsolutions.nfc.plugin.NfcPlugin
W/System.err( 1380):    ... 17 more
W/System.err( 1380): Caused by: java.lang.ClassNotFoundException: com.chariotsolutions.nfc.plugin.NfcPlugin in loader dalvik.system.PathClassLoader[/data/app/com.example.foo-1.apk]
W/System.err( 1380):    at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:240)
W/System.err( 1380):    at java.lang.ClassLoader.loadClass(ClassLoader.java:551)
W/System.err( 1380):    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
W/System.err( 1380):    ... 17 more
I/System.out( 1380): Error adding plugin com.chariotsolutions.nfc.plugin.NfcPlugin.
D/PluginManager( 1380): exec() call to unknown plugin: NfcPlugin

Additional information:
Cordova Version: 3.3.1-0.4.2
Project (default): https://github.com/chariotsolutions/phonegap-nfc/blob/master/doc/GettingStartedCLI.md

**Comment by allannaranjo** [comment]
Hi Don, I'm getting an exception when I do:

nfc.addNdefListener(app.onNFC, function(){
	alert("Listener added...");
}, function(e){
	alert("Error adding listener added..." + JSON.stringify(e));
});

The exception says: "Class not found", any ideas on how to get the plugin to work?

Using: 
phonegap 4.2.0-0.24.2
Samsung Galaxy S3 with Android 4.2.2

Thanks
