### ISSUE TITLE
undefined on NFC reader

### ISSUE THREAD

**Issue by cilluo** [chariotsolutions/phonegap-nfc#132]
my code is

---

function ArletndefMessage(nfcEvent) {

  var tag = nfcEvent.tag,
      ABCD = tag.ndefMessage;

```
   alert(ABCD);
```
## }

I always show "undefined"
## but I can read only ID by

function ArletndefMessage(nfcEvent) {

  var tag = nfcEvent.tag,
      ABCD = tag.id;

```
   alert(ABCD);
```
## }

how can I read other Value (tag.ndefMessage, tag.type, tag.maxsize)?

thanks.

**Comment by mountainclimbing** [comment]
Hi mates!

This issue still persists. Anyone with a working message content that just the ID?

**Comment by don** [comment]
@mountainclimbing it sounds like you have a different problem, can you open a new issue with more details?

**Comment by mountainclimbing** [comment]
No mate. @don 
"but if "avavav = tag.ndefMessage;" >>>>> "avavav = tag.id;" >>>>>>> alert can show ID of NFC tag.
I don't know how to read tag.ndefMessage value to not show "undefind" ."

Am relating to this. When you change avavav = tag.ndefMessage; you get undefined but tag.id; gives you the ID. I need an implementation of reading the Message/Value of the Tag

**Comment by don** [comment]
Are you using [nfc.addNdefListener](https://github.com/don/phonegap-nfc#nfcaddndeflistener)?

If so and you're getting an undefined tag.ndefMessage, I suspect that you're reading a Mifare Classic NFC tag on a device that has a Broadcom NFC chip and doesn't support Mifare Classic tags.

**Comment by mountainclimbing** [comment]
No mate! Am using nfc.addTagDiscoveredListener

    nfc.addTagDiscoveredListener (
        function (nfcEvent) {
            var tag = nfcEvent.tag,
            //vv = tag.ndefMessage;
vv = tag.id;
alert(vv);

**Comment by don** [comment]
You need to use addNdefListener if you want NDEF messages. addTagDiscoveredListener scans NDEF and non-NDEF tags but never returns NDEF info. See https://github.com/chariotsolutions/phonegap-nfc#multiple-listeners

**Comment by mountainclimbing** [comment]
Cheers mate!
Maybe you might even help me on how to get values on an input field after
every NFC read.
https://stackoverflow.com/questions/50734636/how-to-show-nfc-scan-results-on-input-text
