### ISSUE TITLE
Encrypt/Decrypt Tags

### ISSUE THREAD

**Issue by joepegler** [chariotsolutions/phonegap-nfc#137]
Are there any plans to add functionality to encrypt/decrypt tags as they are written/read? I have a version that does this here:

https://github.com/joepegler/phonegap-nfc-aes

I'm quite new to this sort of thing, but I'm writing a thesis on your excellent library and figured I'd look into including a couple of useful methods to keep payloads a secret. My version hasn't been optimized or anything like that, but if you do think it might be useful then let me know if you think it's a worthwhile avenue to explore and I'll try and make it a bit neater. I've effectively merged a JavaScript AES Encryption library into your 'phonegap-nfc.js' file, and used it to read and write tags with AES Encryption. 

The two methods I've added are

``` javascript
nfc.addAesNdefListener(callback, [onSuccess], [onFailure], [myKey]);
```

and

``` javascript
nfc.aesWrite(message, [onSuccess], [onFailure], [myKey]);
```

where 'myKey' is a 16|24|32 length hexadecimal string of the users choice.

**Comment by yannicknya** [comment]
@joepegler , are you still working on your project aes encryption? I'm interested
