### ISSUE TITLE
Add iOS support

### ISSUE THREAD

**Issue by JohnMcLear** [chariotsolutions/phonegap-nfc#139]
Apple announced NFC in the iPhone 6..

This doesn't mean NFC will be usable by third party apps, we will have to wait and see what the API looks like and get a hands on experience..

It's possible Apple will limit NFC to payments only <-- this was the case until late 2016

**Comment by dimitrilahaye** [comment]
Hey! Someting new with iOS support? ;)

**Comment by JohnMcLear** [comment]
Why would there be?  Did apple open up their api?

----- Reply message -----

**Comment by dimitrilahaye** [comment]
Uh good question! I don't hear yet about it :/ Sorry for inconvenience ;)

**Comment by don** [comment]
There is no news. Apple *could* announce new APIs at WWDC, but I wouldn't bet on it.

**Comment by dimitrilahaye** [comment]
Ok I see. Thanks ;)

**Comment by JohnMcLear** [comment]
+1 they aren't announcing it I'm 99.9% sure they never will support it.

----- Reply message -----

**Comment by don** [comment]
Hey @JohnMcLear looks like we might be able to read NFC on iOS https://developer.apple.com/documentation/corenfc

**Comment by dpa99c** [comment]
@don 

> Reading NFC NDEF tags is supported on iPhone 7 and iPhone 7 Plus.

Looks like I'll need a iPhone upgrade to test it though.

**Comment by JohnMcLear** [comment]
It'll be interesting to see what type of performance they get with such a small antenna.  I can imagine the operating range performance will be similar to that of the HTC One M8.

Feels like Apple coming to the party a little too late but let's see how it goes!  I have my developer account ready to go Don I just don't have a developer machine to build any binaries so hopefully I will be able to test w/ out a Mac but I doubt it :(

**Comment by don** [comment]
@JohnMcLear I wrote some native code, but I need to put iOS 11 on my phone to test. We'll see how it works ¯\_(ツ)_/¯. After that, I'll look at building this into the Cordova plugin.

**Comment by JohnMcLear** [comment]
I think I have a green light from NFC Ring to get hardware to test on..  Watch this space!

**Comment by don** [comment]
@JohnMcLear @dpa99c I verified NFC needs iPhone 7. It fails as not supported on 6s. (But you might want to just wait and get in iPhone 8 in the fall.)

**Comment by JohnMcLear** [comment]
Hrm yeah I'm gonna need both as I will need to test antenna matching, I can see this getting expensive quick -_-

**Comment by HashNotAdam** [comment]
I build an app where NFC is the real hook and so would love to get this out swiftly upon iOS 11 release. I had an iPhone 7 and development set up so, if I can provide any support, please let me know.

**Comment by grundyoso** [comment]
iPhone7 NFC reader system not the finest... I put together this benchmark: 

https://flomio.com/2017/06/iphone7-nfc-reader-performance-tests/

I'll be testing the NFC Ring and a wide variety of tag geometries and types next. Let me know if you want something specific tested. Reader performance on front and back of iPhone7 is equivalent.

**Comment by scottire** [comment]
@JohnMcLear I've forked master here and did a bit. Can you post here if you have a branch with any work so far for this issue.

**Comment by JohnMcLear** [comment]
We're still waiting on benchmark test results and will decide on our approach from those.  We hope to have them this week.

**Comment by erikm30** [comment]
Sorry, I am confused here - What kind of benchmark results ? Anything someone else could support? I have accesss to different tag types, and also the hardware.

**Comment by JohnMcLear** [comment]
@erikm30 drop me through an email we will ship you some NFC Rings to play with :)

**Comment by erikm30** [comment]
Thanks for the offer - would really love to see the plugin officially announced ..

**Comment by scottire** [comment]
I pushed to a fork on my account with a first version of this with iOS. It uses a different listener, which isn't good and needs to be changed to merge with the addNdefListener function.

**Comment by don** [comment]
I added iOS support on the [ios branch](https://github.com/chariotsolutions/phonegap-nfc/tree/ios).

You'll need to install the plugin from Github rather than NPM

    cordova plugin add https://github.com/chariotsolutions/phonegap-nfc#ios

See the README for more details https://github.com/chariotsolutions/phonegap-nfc/tree/ios#ios-notes

**Comment by jlkalberer** [comment]
@don - any reason why this hasn't been merged to master?

**Comment by don** [comment]
@jlkalberer I'm planning on releasing once XCode 9 is released.

**Comment by gregavola** [comment]
@don It should be out now?

**Comment by don** [comment]
iOS is in 0.7.0 https://www.npmjs.com/package/phonegap-nfc
