### ISSUE TITLE
First Scan fails

### ISSUE THREAD

**Issue by chrizy** [chariotsolutions/phonegap-nfc#144]
We have an issue with our app where the first and only the first scan fails after the app is installed or waked up.

CORDOVA 3.5.0, tested on android 4.1 & 4.2.2

Code snip
"Success" is fired OK when the app loads, scan event only fires on second scan.

            function fobService($http, $rootScope) {
                var _this = this;
                this.$http = $http;
                this.$rootScope = $rootScope;

                nfc.addNdefListener(function (nfcEvent) {
                    _this.id = nfc.bytesToHexString(nfcEvent.tag.id); // nfc.bytesToString(nfcEvent.tag.ndefMessage[0].payload);

                    var data = serviceBase + _this.id;

                    _this.$http.get(serviceBase + _this.id).success(function (response) {
                        _this.state = response.success;

                        _this.unused = true && (response.status == 99 /* NoKeyAllocated */);
                        _this.state = response.success;
                        var r = { id: _this.id, status: response.status, state: response.success };

                        $rootScope.$broadcast('fobScanned', r);
                    }).error(function (err, status) {
                        alert("Error in fob lookup, http error " + status);
                    });
                }, function () {
                    alert("Success.");
                }, function () {
                    alert("Error no NFC on device, or NFC not enabled");
                });

**Comment by rogervinas** [comment]
Found the same issue in my app.

If I only use <b>addNdefListener</b>:
* First scan's action is <b>NfcAdapter.ACTION_NDEF_DISCOVERED</b> so <b>ndef-mime</b> callback is executed. 
* Next scans' actions are <b>NfcAdapter.ACTION_TECH_DISCOVERED</b> so <b>ndef</b> callback is executed.

I've tested 2 workarounds and they work fine (hope they won't have side effects):

1. Modify java <b>NfcPlugin.parseMessage</b> method to execute <b>ndef</b> callback instead of <b>ndef-mime</b>. From javascript only register the <b>ndef</b> callback <b>addNdefListener</b>.
2. Use only <b>addMimeTypeListener</b>, with the correct mimeType (in my case text/plain). In this case all scans' actions are <b>NfcAdapter.ACTION_NDEF_DISCOVERED</b> so <b>ndef-mime</b> callback is executed, first scan included.

**Comment by don** [comment]
@rogervinas does your first NFC scan open the app with an intent defined in the android manifest file? If so, the 2nd work around is the "official" way to do this.

**Comment by rogervinas** [comment]
@don I don't have any intent defined in the android manifest file related to NFC, should I have one if I am using <b>addNdefListener</b>?
I am applying the 2nd workaround and only using <b>addMimeTypeListener</b>, it is working fine so far.
thanks!

**Comment by don** [comment]
The intent filter is only required to launch the app when scanning a NFC tag.

What phone are you seeing this on? What version of Android is it running? Do you want until after device ready is called before processing NFC tags?

**Comment by rogervinas** [comment]
Ok, I don't need to launch the app when scanning a NFC tag. I only need to scan NFC tags within the app.
I am using a Samsung Galaxy Young GT-S6310N.
Android 4.1.2 (Jelly Bean).

**Comment by don** [comment]
@rogervinas I'm not seeing this on my phones with Android 4.4+. I think this is either a Samsung or Android 4.1 issue. For now stick with your workaround.

**Comment by clintgh** [comment]
I experienced this issue too. I have an app that creates a listener on a tap of a button and it is not working on first scan, but it does on second (exactly how they described it), my workaround is I created an ndefListener that does nothing upon scan on DEVICEREADY.

**Comment by obiwarn** [comment]
We have the same issue here.
First scan after app start/wake fails.

Samsung Galaxy Young 2

**Comment by don** [comment]
@clintgh @obiwarn make sure you're waiting until device ready to do any Cordova api calls. I haven't been able to duplicate this, so I think it's an Android or Device specific issue. If you can create the simplest cordova app that duplicates the problem, I can try and duplicate with my hardware.

**Comment by obiwarn** [comment]
The device makes a scanning "success" sound (Not the sound it makes when it fails to read the tag). But the event seems to be not caught by any of the plugin events. (sorry for my english)

Oh and I use the plugin with Meteor.

**Comment by don** [comment]
@obiwarn can you get me a simple project that demonstrates this?

**Comment by don** [comment]
@obiwarn Look at https://github.com/chariotsolutions/phonegap-nfc/issues/144#issuecomment-99841539. @rogervinas has the same phone as you and was seeing a `ndef-mime` event fired on the first tag scan. (This seems like a device specific issue.)

If that is the case, add a 2nd listener as a work around.

    // your existing listener
    nfc.addNdefListener(app.onNfc, success, failure);

    // add a 2nd listener for the mime type
    nfc.addMimeTypeListener('text/plain', app.onNfc, success, failure);

**Comment by obiwarn** [comment]
@don 
BTW: I had to guess the parameters for the callback, success and error functions. I am new to JS. Is there a better way to retrieve them or  did you just miss it in the docs? (e.g. onNfc(result, error) , onError(error) )

addMimeTypeListener has the same lag on startup (i.e. only works 2nd time). It also causes my phone to open a system dialog ("Empty tag detected"). So it is not usable for me.

addTagDiscoveredListener works the first time. I just found out that it also retrieves the ndef id. 
So this seems like a solution. 

I will try...

**Comment by obiwarn** [comment]
Yes. addTagDiscoveredListener works great.

**Comment by don** [comment]
@obiwarn This sounds like a device specific problem. Since you have a work around, I'm closing this issue. If you continue to have the problem, re-open the issue with **sample code** that demonstrates the issue.

The documentation could be better about the callback parameters. For now look at the sample projects for more details. (There's also a [book](http://www.amazon.com/gp/product/1449372066).)

**Comment by clintgh** [comment]
Hi @don I'm still experiencing the same issue.
My first scan does not work, but the second time works.

Please see attached .txt file for the logs. 
[log-work.txt](https://github.com/chariotsolutions/phonegap-nfc/files/158214/log-work.txt)
[log-nowork.txt](https://github.com/chariotsolutions/phonegap-nfc/files/158215/log-nowork.txt)

There is a major difference between the logs when it didn't work and the logs when it worked. 
One difference is in the log that didn't work, it is showing **TECH_DISCOVERED ** but in the one that worked it is showing **NDEF_DISCOVERED**

**Comment by clintgh** [comment]
Found my solution buried inside the Pull Request:

#218

**Comment by don** [comment]
See #217 Changes published in v1.0.1
