### ISSUE TITLE
Add method to check NFC enabled

### ISSUE THREAD

**Issue by don** [chariotsolutions/phonegap-nfc#146]
Add explicit method to check NFC status. Currently error callbacks get NO_NFC for devices without NFC and NFC_DISABLED when the user has turned NFC off.

```
// call success if nfc is enabled 
// call failure if nfc is disabled or does not exist (check the return code)
nfc.enabled(success, failure);
```

**Comment by armaldio** [comment]
Hello, 

I'm trying to do that 

```
nfc.enabled(function () {
    //succes
}, function (err) {
    //Failure
});
```

But all i get is  : Uncaught TypeError: Cannot read property 'enabled' of undefined

Can you help me ?

**Comment by JohnMcLear** [comment]
make sure you do this AFTER the device ready event has fired.

**Comment by armaldio** [comment]
That's ok and all other functions are working well

**Comment by Faustxx** [comment]
This method is not working correctly for me.

I get NO_NFC in devices without NFC, and NFC_DISABLED when this feature is manually disabled in the device, but the success callback is not being called when the NFC is enabled.

I can read NFC tags without problem, I just don't get the NFC_OK message.

I'm using:
Cordova 4.2.0
NFC 0.6.1 (retrieved with this command: cordova plugin add com.chariotsolutions.nfc.plugin")
Sony Xperia M
