### ISSUE TITLE
How to read Mifare cards sectors and blocks

### ISSUE THREAD

**Issue by Devofure** [chariotsolutions/phonegap-nfc#153]
Hi, Im trying to read from a Mifare Card with you plugin, in Android the Mifare Class is used to connect and read the data, but if I get the tag as a Json from your plugin, How could I read the data as this: 
mifareClassic.connect();
mifareClassic.authenticateSectorWithKeyA();
mifareClassic.getBlockCountInSector();
mifareClassic.readBlock();

Is it possible to do that with javaScript?
Im using a Android mobile that can read Mifare.

**Comment by sutriadi** [comment]
@valemunoz, @don, i need to read sectors and blocks too. where line on NfcPlugin.java that need to change? btw, i dont know java programming.

**Comment by don** [comment]
@sutriadi there are 2 pull requests #155 and #156 that have code for reading mifare. I haven't had time to review and clean up before merging. Give them a try and see if it works for you.

**Comment by lufa12** [comment]
Hi, I try the code for reading mifare but it's not working for me. Someone have a sample code ?

**Comment by lecmns** [comment]
> @JohnMcLear I did it! ... I change the nfc plugin and add 2 functions one who reads and returns the data from all sectors and the other reads a sector specific block. code so no more optimal for the moment but it works :) if anyone needs it let me know

@valemunoz, where do i find this plugin code? We are trying to do a similar read from Ionic stack, to read bytes / values from all blocks / sectors and they dont follow NDEF formats. Please help to get a walk through on this solution you did..
