### ISSUE TITLE
Null error

### ISSUE THREAD

**Issue by armaldio** [chariotsolutions/phonegap-nfc#163]
Hello,
I successfully be able to read a tag but when I try to share, write or erase all that i got is a null error.
What does it mean and how to solve it ?
Am I going the wrong way ?

**Comment by armaldio** [comment]
Great, i learn something cool ^^
Is there a way to filter results ?

**Comment by armaldio** [comment]
![android device monitor](https://cloud.githubusercontent.com/assets/3089715/5654541/76310cf6-96c4-11e4-875b-7482e1c4f711.jpg)

This is the log, filtering with "nfc" while scanning a tag

**Comment by armaldio** [comment]
Ok, i'm sorry, i solved the problem by removing alerts
It cause trouble in using nfc and probably break the functions
So don't display alerts while using nfc ^^
Thank you for you help and your attention

**Comment by don** [comment]
@armaldio I'm glad you got this working

**Comment by clintgh** [comment]
I encountered this issue once, and one reason is because I immediately removed or distanced the device from the NFC sticker before it succeeds/finishes the writing process.
