### ISSUE TITLE
Firefox OS support

### ISSUE THREAD

**Issue by Hollerweger** [chariotsolutions/phonegap-nfc#164]
Is a support for FirefoxOS planned? 
https://developer.mozilla.org/en-US/docs/Web/API/MozNFCTag

**Comment by don** [comment]
I'd like to support FirefoxOS. I talked to them in October and although were APIs, only privileged apps could use them. IIRC, apps developers write can't use the NFC APIs yet. Do you know if that changed?

**Comment by joedarc** [comment]
Any word on firefoxOS support?

**Comment by don** [comment]
@joedarc I haven't heard anything more about FirefoxOS, but I haven't been following the issue. If you see any example NFC apps for FirefoxOS, that means they have opened up the API to non-system apps and I can probably implement support in the plugin.
