### ISSUE TITLE
Phonegap Build support

### ISSUE THREAD

**Issue by Medioman92** [chariotsolutions/phonegap-nfc#165]
is planned in the future the support to the PhoneGap build system ?

**Comment by JohnMcLear** [comment]
Afaik it already does
----- Reply message -----

**Comment by don** [comment]
This plug is on PhoneGap Build https://build.phonegap.com/plugins/1058

FWIW you can now add any plugin from the cordova plugin repo to your phonegap build project  http://phonegap.com/blog/2014/12/09/phonegap-build-new-features/
