### ISSUE TITLE
Windows 8.1 support?

### ISSUE THREAD

**Issue by drsouly** [chariotsolutions/phonegap-nfc#168]
First off all, thanks for your hard work!

Is there a way to support the windows platform?

Cheers

**Comment by don** [comment]
Windows 8? Do you have a computer/tablet with a built in NFC reader or an external reader?

**Comment by drsouly** [comment]
I'm currently evaluating the possibility of using NFC with windows tablets. According to this slightly outdated list, there should be windows devices with NFC.

http://en.wikipedia.org/wiki/List_of_NFC-enabled_mobile_devices

We'll wait buying such a device until we know if its theoretically possible.

Thanks for your quick response.

**Comment by don** [comment]
I think the Windows 8 works well with Cordova and the Proximity APIs should be similar to the Windows Phone APIs.  This should be possible. (disclaimer: I'm not a windows developer.)  It would be easier to develop if the proximity apis work external NFC readers.

**Comment by don** [comment]
See https://github.com/chariotsolutions/phonegap-nfc/pull/182

**Comment by don** [comment]
@jlkalberer added support for Windows 8.1 in #182. This is available in phonegap-nfc 0.6.2
