### ISSUE TITLE
Check if NFC hardware is present

### ISSUE THREAD

**Issue by m-menon** [chariotsolutions/phonegap-nfc#174]
hi,

Is there a way to check if NFC hardware is present in the first place - irrespective of whether NFC is turned on or off?

Thanks,
M&M

**Comment by m-menon** [comment]
I guess the below should work.

<code>
nfc.enabled(
  function() {alert('yes!')},
  // msg is one of NO_NFC (no hardware support) or NFC_DISABLED (supported but disabled)
  function(msg) {alert(msg)}
);
</code>

**Comment by don** [comment]
@m-menon `enabled` will return NO_NFC if the device doesn't support NFC

https://github.com/chariotsolutions/phonegap-nfc#nfcenabled

**Comment by m-menon** [comment]
cool...thank you
