### ISSUE TITLE
Error occured in NfcPlugin.java

### ISSUE THREAD

**Issue by polim1022** [chariotsolutions/phonegap-nfc#179]
hi, i follow all the steps to install the plugin but it happens that there is some errors occur in NfcPlugin.java. Error says that : the method sendJavascript(String) from the type CordovaWebView is deprecated. What does it mean? Sorry i'm just a newbie. I'm doing this for my FYP. Urgent to solve this problem.How to solve this? I'm using cordova 4.3.0.

Steps i have done to install nfc plugin in my project:
cordova create nfc com.example.nfc NFC
cd nfc
cordova platform add android
cordova plugin add com.chariotsolutions.nfc.plugin
cordova build

This is the error after open in eclipse:
![nfcplugin](https://cloud.githubusercontent.com/assets/11718384/6895240/b0b107be-d710-11e4-8ebb-75f377ee7b70.png)

**Comment by don** [comment]
That deprecation method is a warning, not an error. The deprecated messages means that `sendJavascript` will be removed in a future version of Cordova. You can safely ignore the warning and your app will work fine.

**Comment by polim1022** [comment]
Ya..you are right. I just run it and it is fine. Thanks for your fast reply!
