### ISSUE TITLE
write only one record on multiple records 

### ISSUE THREAD

**Issue by lezardrouge** [chariotsolutions/phonegap-nfc#181]
Hello,
Is there a way to write only in a record without deleting the others already set ?
For example my payload contains a record with text and another with some other data, let's say an url ; I want to rewrite only the text (exact same length) and do not touch the url. 
I would like to avoid to rewrite everything because I have 8ko of data and it takes too much time (and it's also dangerous to rewrite this data).
Thank you

**Comment by JohnMcLear** [comment]
You should do a read function, append to an object, then write...

**Comment by don** [comment]
@lezardrouge the underlying APIs only write the whole NDEF message, so @JohnMcLear's read, append and write solution is the best way to do this.

**Comment by lezardrouge** [comment]
Thank you both for your answers. 
@don when you talk about the underlying API, is it a limitation of Cordova or it would be the same problem with a native app ?

**Comment by don** [comment]
@lezardrouge you'd have the same problem with native Android too. You need to write the complete NDEF message, you can't update an existing message.
