### ISSUE TITLE
Can't Read data (payload) from non-NDEF tag

### ISSUE THREAD

**Issue by BenCohenBenCohen** [chariotsolutions/phonegap-nfc#186]
Hi,
I'm trying to read from my non-NDEF NFC card.
the only ACTION that is triggered is ACTION_TAG_DISCOVERED and i only can read the tag_info.

the tag's techs are "NfcB" and "IsoDep"

can anyone please help me get the data?

**Comment by don** [comment]
@BenCohenBenCohen this plugin only supports NDEF. Android supports NfcB and IsoDep so it's possible to extend this plugin to do what you need.

**Comment by BenCohenBenCohen** [comment]
Thanks!
