### ISSUE TITLE
Question: Is is possible to disable Beam (share)

### ISSUE THREAD

**Issue by tsukasa1989** [chariotsolutions/phonegap-nfc#200]
Hello,

Is it possible with the current version to disable NFC Beam? Because for some screens of my application I do not want Android to "zoom" out so the Android Beam takes over. 

I know you can do this within Android:

    NfcAdapter adapter = NfcAdapter.getDefaultAdapter(this); 
    adapter.setNdefPushMessage(null, this, this);

Is there any way to simulate that action? To pass null into the first param.

Thanks

**Comment by tsukasa1989** [comment]
nfc.unshare(); already calls this method, so on startup I just call nfc.unshare();

**Comment by don** [comment]
I think that Android defaults to beaming an AAR record for your app if you don't define one. Calling `nfc.unshare()` will work. I think there's also a way to disable this in the AndroidManifest.xml too, but I can't find a link right now.
