### ISSUE TITLE
Trying to Compile/Build NFC-Stuff for Blackberry10

### ISSUE THREAD

**Issue by LaermTot** [chariotsolutions/phonegap-nfc#203]
Hell I tried to 
> git clone https://github.com/chariotsolutions/phonegap-nfc.git
> cd phonegap-nfc
> ant build-javascript

>> Buildfile: build.xml not found
What am I missing here ?

Volker

**Comment by don** [comment]
Duplicate of #202

**Comment by don** [comment]
`ant build-javascript` was for BlackBerry 7
