### ISSUE TITLE
Perform multiple tasks within the mobile-app when a NFC tag is scanned

### ISSUE THREAD

**Issue by anzrnr** [chariotsolutions/phonegap-nfc#211]
Hi Guys, 

While we code NFC chip to perform multiple task, I was wondering if it can be made to perform multiple activities within the app. Say after reading the NFC tag can it open an app+open a particular content within the app.

Ex: News App, When I tap the NFC chip, 1. It opens News app + 2. Open Sports category news.
Or can it also prompt for app install from store and re-tapping do above 2-tasks.?

What coding does it require at NFC chip?
Any specific mobile-app development is required to accommodate this?

Please help me understand it better and any reference will be much oblige.
Thanks in advance.

**Comment by don** [comment]
This plugin provides a way for your app to read the data from an NFC tag. Based on the data that is ready, it's your responsibility to navigate to the correct place in the app.

You can launch your app when an NFC tag is scanned if you create the proper filter in the application manifest. See [Launching your Android Application when scanning a tag](https://github.com/chariotsolutions/phonegap-nfc#launching-your-android-application-when-scanning-a-tag).

If the NFC tag contains an [Android Application Record (AAR)](http://developer.android.com/guide/topics/connectivity/nfc/nfc.html#aar) and the user does not have your app installed, Android will open the app store.
