### ISSUE TITLE
support windows

### ISSUE THREAD

**Issue by mobidev111** [chariotsolutions/phonegap-nfc#214]
just as a suggestion: is support for windows possible? Lot's of professional devices have RFID/NFC readers

probably the API support across the windows platforms got better with the unified api in windows 10

**Comment by don** [comment]
Windows is supported, but only tested on Windows Phone 8.1 so far.

If you `cordova platform add windows` this should support Windows Phone 8.1, Windows 10 and maybe(?) Windows 8.1. If you find problems, create a new issue with details.

**Comment by JohnMcLear** [comment]
I think this can be closed..
