### ISSUE TITLE
addTagDiscoveredListener is not working after addNdefListener is being registered

### ISSUE THREAD

**Issue by Swathi8** [chariotsolutions/phonegap-nfc#237]
Hi,

I'm using [addTagDiscoveredListener](https://github.com/chariotsolutions/phonegap-nfc#nfcaddtagdiscoveredlistener) and [addNdefListener](https://github.com/chariotsolutions/phonegap-nfc#nfcaddndeflistener) methods to discover is any nfc tag found(if so, write ndefMessage to tag) and read data from nfc tag respectively. At any point of time only one of the method will be registered based on some condition.

I'm using [Backbone](http://backbonejs.org/) in front-end. when view renders, registering any one of these methods based some condition and removing listeners on destroy of the view.

Once `addNdefListener` is registered and remove it on view destroy. And registering `addTagDiscoveredListener` method on view render is not calling callback of `addTagDiscoveredListener` method. Where as it works before registering the `addNdefListerer`.

Don't know what is happening here!, Why `addTagDiscoveredListener` is not working once `addNdefListener` method is register. Is anything I'm doing wrong?

**Comment by don** [comment]
Android always calls the most specific listener for any tag. If you have `addTagDiscoveredListener` and `addNdefListerer` NDEF tags always end up with `addNdefListerer`

I don't recommend removing listeners, I'd always keep both listeners added.
