### ISSUE TITLE
Supported tags

### ISSUE THREAD

**Issue by jszersze** [chariotsolutions/phonegap-nfc#238]
Hello, 

I would like to know if there are any plans to update support for some additional tags. Here is some info about the one that I need specifically:

NXP MIFARE Classic 1k 

Please let me know if there is additional information you require about this tag.

**Comment by don** [comment]
Mifare Classic tags are supported on phones with the  NXP chipset. Unfortunately phones with the Broadcom chipset don't support Mifare Classic.
