### ISSUE TITLE
addNdefListener error on Windows 10

### ISSUE THREAD

**Issue by rancano** [chariotsolutions/phonegap-nfc#239]
On Lumia 950XL nfc.addNdefListener return NO_NFC_OR_NFC_DISABLED. When i use nfc.addTagDiscoveredListener it detects the tag without error, but i don't have any information writen on it.

**Comment by don** [comment]
On Windows, addTagDiscoveredListener only detects that presence of the tag. There's no way to get the meta data, that function was added so you could write new messages to an unformatted tag.

nfc.addNdefListener should work on Lumia 950XL, it's possible you hit a bug. Can you create a simple reproducible test case and post the code?
