### ISSUE TITLE
NFC running in Android sleep mode (background service or wakelock)

### ISSUE THREAD

**Issue by ShaunBrassell** [chariotsolutions/phonegap-nfc#240]
Hi there, thanks for the epic plugin! 

Everything works 100% with tag scanning, and app launching via the Intent-Filter in order to scan a tag. I now have a need to keep the NFC active when the phone is asleep. This is for a specialized application with a dedicated phone. I have been playing around with wakelocks, but have had not joy so far. Any suggestions?

**Comment by don** [comment]
Unfortunately I don't think there's a way to scan tags when the phone is asleep.
