### ISSUE TITLE
[Windows Universal / Android/ IOS] NFC Tag/ID

### ISSUE THREAD

**Issue by Webrow** [chariotsolutions/phonegap-nfc#241]
So the documentation states the NFC Tag/ID can only be read on BB7 and Android devices. 
Is there any way to register the meta data on the Windows universal (10) devices? 

I was thinking about reading it with a compatible reader, and writing it into the tag? 
I hope someone has a view on this or a solution.

**Comment by don** [comment]
@Webrow I don't think there are any Windows APIs to get the meta data. If you find documentation or an example on how to do this in Windows, I can probably add it into the plugin.
