### ISSUE TITLE
Android noHistory attribute

### ISSUE THREAD

**Issue by adamrenner** [chariotsolutions/phonegap-nfc#243]
The Readme states:
"We have found it necessary to add android:noHistory="true" to the activity element so that scanning a tag launches the application after the user has pressed the home button."

I am not sure that this is entirely necessary.  My application seems to launch fine even without the noHistory attribute being set.

or, maybe I am not understanding the issue.

**Comment by don** [comment]
That comment is from Android 2.3, it's possible it doesn't apply anymore.

IIRC, without `android:noHistory="true"` a new copy of the app was launched instead of reusing the copy that was running.  If your app is working without, feel free to ignore that section.
