### ISSUE TITLE
I am not able to retrieve NFC tags

### ISSUE THREAD

**Issue by jwillmer** [chariotsolutions/phonegap-nfc#247]
This function:

```
nfc.addTagDiscoveredListener(function (nfcEvent) {
    console.log("discovered");
    console.log(JSON.stringify(nfcEvent));
}, function () {
    console.log("Discovering NFC Messages.");
},
function (error) {
    console.log("Failed to discover NDEF.");
});
```

outputs this:

```
{"isTrusted":false,"tag":{"id":[91,7,-33,-4],"techTypes":["android.nfc.tech.NfcA","android.nfc.tech.MifareClassic","android.nfc.tech.NdefFormatable"]}}
```

but the listener never fires a event:

```
nfc.addNdefListener(function (nfcEvent) {
    console.log("listener");
    console.log(JSON.stringify(nfcEvent));
}, function () {
    console.log("Listening for NFC Messages.");
},
function (error) {
    console.log("Failed to add NDEF listener.");
});
```

I tried to use `addMimeTypeListener` with one of this MIME types (`android.nfc.tech.NfcA`,`android.nfc.tech.MifareClassic`,`android.nfc.tech.NdefFormatable`) but I also don't get a result.

My test NFC card contains a number (plain text). Something like: `123456789`

**Comment by don** [comment]
What phone are you using?

Based on the output above, you're scanning a Mifare Classic tag.  Newer phones with Broadcom NFC chips don't support Mifare Classic tags for NDEF.

**Comment by jwillmer** [comment]
@don I use a `Xiaomi Mi 5` but I cannot find any specs that tell me which NFC chip it has :(

**Comment by jwillmer** [comment]
Android Version `6.0`

**Comment by don** [comment]
Maybe it's a permission problem. I haven't updated this plugin for Android 6 permission yet. Can you edit config.xml and target Android-22?

    <platform name="android">
        <allow-intent href="market:*" />
        <preference name="android-targetSdkVersion" value="22" />
    </platform>

**Comment by jwillmer** [comment]
If I change it in the project `config.xml`
```
 <platform name="android">
    <allow-intent href="market:*" />
    <preference name="android-targetSdkVersion" value="22" />
  </platform>
  <platform name="ios">
     ...
```

 I get the following error: 
`Failure [INSTALL_FAILED_PERMISSION_MODEL_DOWNGRADE]`

**Comment by don** [comment]
That error means you need to delete the app from your phone before installing the new one.

**Comment by jwillmer** [comment]
I updated the comment - sorry, was to slow ;)

**Comment by jwillmer** [comment]
FYI this [reader on GitHub](https://github.com/nadam/nfc-reader) is available in the Play Store and can display the value of the NFC card.

**Comment by jwillmer** [comment]
Maybe your are missing references to `Mifare`?

@nadams source file:
https://github.com/nadam/nfc-reader/blob/master/src/se/anyro/nfc_reader/TagViewer.java#L37-L38

**Comment by don** [comment]
That Java code has worked with Mifare for a long time. It's unlikely that is the problem. 

What happened after you installed the android-22 version of the app? Attach more logs from adb if it's still failing.

**Comment by don** [comment]
@jwillmer try this sample project https://github.com/don/phonegap-nfc-issue-247

For phones that support Mifare Classic you'll get NDEF data. For other phones like Nexus 4 or Samsung S4 that don't support Mifare Classic, you'll get some tag metadata. Both screenshots below are from the same app scanning the same MifareClassic NFC tag.

Nexus 5X

![nexus5x](https://cloud.githubusercontent.com/assets/3133/17158267/304fe1a0-5363-11e6-8735-18ae6f886179.png)


Samsung S4

![samsungs4](https://cloud.githubusercontent.com/assets/3133/17158236/e0b1eefe-5362-11e6-8223-41d57117e441.png)

**Comment by jwillmer** [comment]
I tried your solution and the output is this;
![screenshot_2016-07-27-10-54-35_com example phonegap nfc issue247](https://cloud.githubusercontent.com/assets/1503577/17169624/ac2a736e-53e8-11e6-8589-94def1a1ca46.png)

What I don't undeerstand is why another NFC app can display the result/number:
![screenshot_2016-07-27-10-57-24_se anyro nfc_reader](https://cloud.githubusercontent.com/assets/1503577/17169693/07c12d9e-53e9-11e6-878e-e5175b2427c5.png)

**Comment by jwillmer** [comment]
> That Java code has worked with Mifare for a long time. It's unlikely that is the problem.

I don't say your code is bugy but your code might not cover all cases. I am not a Java programer but for me it looks like that [the code](https://github.com/nadam/nfc-reader/blob/master/src/se/anyro/nfc_reader/TagViewer.java#L143) of @nadam gets more information out of the tags. Wdyt?

**Comment by don** [comment]
According to your screenshot, your tag is NdefFormatable, meaning there's no NDEF message on the tag.

The nfc.addNdefListener will only be called when there's an NDEF message on the tag. You need to use nfc.addNdefFormatableListener or nfc.addTagDiscoveredListener to get an event for non-NDEF tags.

Use [NXP TagInfo](https://play.google.com/store/apps/details?id=com.nxp.taginfolite&hl=en) to view the data on the tag.

I updated the demo app to write a message to the tag when it sees a formatable tag. https://github.com/don/phonegap-nfc-issue-247/commit/441314813ed21a91105de338b0f21b5519953884

Alternatively you can write at text record to the tag using [NXP TagWriter](https://play.google.com/store/apps/details?id=com.nxp.nfc.tagwriter&hl=en).

**Comment by jwillmer** [comment]
O.K. but there is still a number on the card I need to read and I am not able to get it with that plugin. Is that intended? For me it is a problem because my app needs to read this cards - not format them.

**Comment by jwillmer** [comment]
I was blind. I found the Id in the result. I needed to format the id to hex then I have it (reversed).

![image](https://cloud.githubusercontent.com/assets/1503577/17205726/74174f0a-54ac-11e6-8f1c-67fbc9bae60b.png)

**Comment by jwillmer** [comment]
@don Thank you for your help, you kept me going :+1:

**Comment by don** [comment]
You're welcome. Since you only need the ID, you can use the tagDiscoveredListener in your app. It should find any tag.

**Comment by riebschlager** [comment]
I'm having a similar issue. I am using `tagDiscoveredListener` and it never seems to be fired. The tablet makes a sound like it is reading successfully, but the `tagDiscoveredListener` callback is never called. The tags I'm trying to scan are `MifareUltralight`.

Any idea what might be happening?

**Comment by jwillmer** [comment]
@riebschlager can you open another issue? This one is closed.
