### ISSUE TITLE
Plugin exception on Windows Phone

### ISSUE THREAD

**Issue by jwillmer** [chariotsolutions/phonegap-nfc#248]
I have a Windows Phone 950 and compiled my app as a Windows Phone (universal) app. I get the following error then I try to scan a NFC card.

![code error](https://cloud.githubusercontent.com/assets/1503577/17173845/7e1ee2e2-53fd-11e6-812d-d0fd3d33ed2e.png)

I used the same card as in issue #247 and I also deployed/tested the project to an Android without having this problem.

**Comment by jwillmer** [comment]
Foud the issue. In Windows Phone the `tag.id` is empty and my convertion

```
var hex = nfc.bytesToHexString(nfcEvent.tag.id)
```

fails.

**Comment by don** [comment]
Newer Windows devices with certain NFC chipsets can get the tag id. Other devices only get the NDEF data from the tag and id will be null.
