### ISSUE TITLE
An example or link to a bulletproof method of reading a tag and it's payload (if any)

### ISSUE THREAD

**Issue by m-menon** [chariotsolutions/phonegap-nfc#253]
hi,

I was wondering if there is a real-world example on reading NFC cards (the tag, and the payload if any). What I mean my "real-world" is that it should be able to employ multiple methods (listeners or something?), with a decent error handler. 

I remember having seen Don mention about "if-not-this-then-that-method" (to increase the chances of reading a nfc card) somewhere but I just can't find the post / link no matter how hard I try :) I am attaching details of the NFC cards that I usually be reading with my app. And also thanks a ton for the excellent plugin.

![screenshot_2016-02-05-12-20-30](https://cloud.githubusercontent.com/assets/10776430/18660711/990e102e-7f44-11e6-84dd-5adea29d5737.png)
![screenshot_2016-08-24-13-03-11](https://cloud.githubusercontent.com/assets/10776430/18660710/990ba60e-7f44-11e6-890e-b82baecb9e51.png)

Cheers,
M.M

**Comment by don** [comment]
There's really no simple answer.

Reading NDEF tags is pretty straight forward with [addNdefListener](https://github.com/chariotsolutions/phonegap-nfc#nfcaddndeflistener), but you need to write code to read the TNF and Type and decoding the payload. 

If you want to handle non-NDEF tags you can add a [addTagDiscoveredListener](https://github.com/chariotsolutions/phonegap-nfc#nfcaddtagdiscoveredlistener)

I use [addMimeTypeListener](https://github.com/chariotsolutions/phonegap-nfc#nfcaddmimetypelistener) to handle tag reads that [launch the app from an intent filter](https://github.com/chariotsolutions/phonegap-nfc#launching-your-android-application-when-scanning-a-tag).

I use [addNdefFormatableListener](https://github.com/chariotsolutions/phonegap-nfc#nfcaddndefformatablelistener) to handle unformatted tags that can have NDEF messages written to them.

It's fine to all all 4 listeners added in one app. Android will call the most specific listener for any tag. It's also find (and often preferable) to share event handlers across listeners so you don't have to duplicate logic.

HTH
