### ISSUE TITLE
nfc.readerMode

### ISSUE THREAD

**Issue by m-menon** [chariotsolutions/phonegap-nfc#256]
hi,

Was wondering if this (nfc.readerMode) is functional and how would I use this? Do I call this before or after adding the Listener? Currently I read the NFC card by the below code

```
    nfc.addNdefListener (
        nfcHandler,
        function () {
            console.log("Success, listener added. You can now scan a tag.");
        },
        function (error) {
            alert("Adding the listener failed.");
        }
    );
```

Thanks

**Comment by don** [comment]
There's no nfc.readerMode.  This would need to be implemented. See #198
