### ISSUE TITLE
remove event listener not working

### ISSUE THREAD

**Issue by jszersze** [chariotsolutions/phonegap-nfc#257]
It looks like the 'removeTagDiscoveredListener' is not removing the function that is being triggered by the event listener. When I try to overwrite the function (as a work around) and set it to an empty function, `myfunc = function(){}` it still gets triggered also. It's almost like it makes another internal copy of this function that becomes unavailable upon event listeners creation. 

Is there any solutions to getting rid of either the event of the function triggered?

**Comment by don** [comment]
Can you create a simple example to demonstrate this problem? That would help me debug the issue.

**Comment by jeremycoppey** [comment]
I'm experiencing the same behavior here, the remove doesn't work. did you already worked on this issue? You need some extra information?
