### ISSUE TITLE
Unable to call different function every time while tapping NFC card

### ISSUE THREAD

**Issue by testaccnt0435** [chariotsolutions/phonegap-nfc#260]
In my app, i have two ionic controllers. First login controller, when tapping NFC card , it will verify the card number and login. Second Dashboard controller, when tapping new NFC card, it will verify the card number and get value from api. But when i tap second NFC card, first controller is also called. I am using 'addTagDiscoveredListener' for read the NFC card. Help me to call different function every time while tapping NFC card. I have this code in both controllers,
var nfcid = nfc.addTagDiscoveredListener(onNfc, win, fail);

**Comment by don** [comment]
I'd set up a NFC service to receive the data from the tags. This way you can have one function that handles the NFC read. Based on the data you get you can dispatch from the NFC service to the proper controller.
