### ISSUE TITLE
Doesn't read Oyster card

### ISSUE THREAD

**Issue by rolandkofler** [chariotsolutions/phonegap-nfc#266]
The London subway card "Oyster card" is not read, what are the possible causes?

**Comment by nestorsilk** [comment]
Oyster card is a mifare desire ev1 card. Works differently. But in case you intend to work with desfire cards , especially in block chain context ( I assume) you can contact me.

**Comment by don** [comment]
This plugin reads and writes NDEF messages on tags. Mifare DESfire tags with NDEF messages should work fine, however like @nestorsilk mentioned that Oyster card is different. 

You can probably use https://play.google.com/store/apps/details?id=com.nxp.taginfolite&hl=en to view the card contents. The Android SDK should have the classes you need to read and write sectors.
