### ISSUE TITLE
W3C Web NFC API draft

### ISSUE THREAD

**Issue by jelhan** [chariotsolutions/phonegap-nfc#267]
Probably api should be rewritten to follow [Web NFC API draft](http://w3c.github.io/nfc/proposals/common/nfc.html). Currently I don't know of any browser implementing it but might make transition easier in long term. Since it would be an breaking change it should land before 1.0 release.

Development has started in [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=520391) and it's under consideration in [Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/webnfcapi/?q=web%20nfc%20). Firefox OS has an NFC Api (also mentioned in #164) but it's not following W3C Web NFC API draft.

**Comment by don** [comment]
Web NFC has been in draft a long time. When it's released I'll see what needs to be done. If you'd like to work on a conversion before let me know and we can collaborate.
