### ISSUE TITLE
iOS build failes in PGB

### ISSUE THREAD

**Issue by mgoetz85** [chariotsolutions/phonegap-nfc#281]
Dear all,

I am trying to developed a very simple prototype for iOS, however PGB always throws an error.
If I remove the plugin / config line

`<plugin spec="https://github.com/chariotsolutions/phonegap-nfc.git" source="git" />`

the build passes successfully.

App-ID is 2814573.

`The following build commands failed:
	CompileC /Users/phonegap/Library/Developer/Xcode/DerivedData/NFC_Test-eeofxxwbgnwiqtdcybqstaxloonf/Build/Intermediates/ArchiveIntermediates/NFC\ Test/IntermediateBuildFilesPath/NFC\ Test.build/Release-iphoneos/NFC\ Test.build/Objects-normal/armv7/NfcPlugin.o NFC\ Test/Plugins/phonegap-nfc/NfcPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/private/tmp/gimlet/2814573/project/cordova/build-release.xcconfig,-workspace,NFC Test.xcworkspace,-scheme,NFC Test,-configuration,Release,-destination,generic/platform=iOS,-archivePath,NFC Test.xcarchive,archive,CONFIGURATION_BUILD_DIR=/private/tmp/gimlet/2814573/project/build/device,SHARED_PRECOMPS_DIR=/private/tmp/gimlet/2814573/project/build/sharedpch`

Any idea?

**Comment by don** [comment]
I’d guess that PhoneGap Build can’t handle NFC on iOS yet. iOS NFC support needs Xcode9 which was just released this week. Typically it takes PGB a bit to implement new feature.

**Comment by zxfrank** [comment]
I also get an error

phonegap-nfc/NfcPlugin.h:11:9: fatal error: 'CoreNFC/CoreNFC.h' file not found
#import <CoreNFC/CoreNFC.h>

@mgoetz85 do you have this error too or different?

**Comment by felipel90** [comment]
+1 @zxfrank

**Comment by psyfreak** [comment]
Same error

**Comment by don** [comment]
Version 0.7.1 of phonegap-nfc now automatically adds the NFC framework to the project. It's possible this fixes the PhoneGap Build problem. This assumes that PhoneGap Build is compiling with Xcode 9.

**Comment by markus-fischbacher** [comment]
Same problem here when building using Ionic Pro Package in the cloud.
Updated phonegap-nfc to 0.7.1 but still the same error present.

Any ideas?

```
[14:39:00]: ▸ In file included from /Users/ionic/builds/project-1/platforms/ios/Cook and Eat - order/Plugins/phonegap-nfc/NfcPlugin.m:7:
[14:39:00]: ▸ /Users/ionic/builds/project-1/platforms/ios/Cook and Eat - order/Plugins/phonegap-nfc/NfcPlugin.h:11:9: fatal error: 'CoreNFC/CoreNFC.h' file not found 
[14:39:00]: ▸ #import
[14:39:00]: ▸         ^ [14:39:00]: ▸ 1 error generated.
```

**Comment by m-kikukawa** [comment]
Same error

**Comment by jpgilchrist** [comment]
Same error here as well. I'm just running cordova, not phonegap build. However, for various (silly) reasons I need to run the build with xcode8.

**Comment by jcesarmobile** [comment]
PGB started using Xcode 9 a few weeks ago, so this probably can be closed

**Comment by don** [comment]
Closing based on https://github.com/chariotsolutions/phonegap-nfc/issues/281#issuecomment-362296136
