### ISSUE TITLE
Multiple NFC Reads for IOS based attendance system

### ISSUE THREAD

**Issue by tvvignesh** [chariotsolutions/phonegap-nfc#282]
Hi,
We have been using this plugin for our Android app and it works very well. We are now trying to build our IOS version of the app (record attendance in a publicly placed kiosk device which in IOS through NFC).

Now, I noticed in the README that 

> The initial iOS version plugin does not support scanning multiple tags (invalidateAfterFirstRead:FALSE) or setting the alertMessage. If you have use cases or suggestions on the best way to support multi-read or alert messages, open a ticket for discussion.

What does this actually mean? Wont I be able to scan multiple NFC tags on same device? 

If yes, When you supply nfc.invalidateSession api to invalidate the session, cant we use the same to invalidate the session after every NFC card is scanned?

Thanks in advance.

**Comment by don** [comment]
@tvvignesh for now you need to call nfc.beginSession before every scan.

Alternately you could write an app to scan multiple NFC tags in one session but that would requires API changes. Give the existing code a try. If you have a different use case and an alternate API lets talk about it.
