### ISSUE TITLE
Automatically Add NFC entitlement

### ISSUE THREAD

**Issue by andreamaioli** [chariotsolutions/phonegap-nfc#284]
Hi,

I've added the following code to the plugin.xml file and now I can just add ios platform and run from cordova. No need to open xcode and manually add the entitlement.

` 
<config-file platform="ios" target="*-Debug.plist" parent="com.apple.developer.nfc.readersession.formats">
      <array>
        <string>NDEF</string>
      </array>
    </config-file>
`

`
    <config-file platform="ios" target="*-Release.plist" parent="com.apple.developer.nfc.readersession.formats">
      <array>
        <string>NDEF</string>
      </array>
    </config-file>
`

Would you consider to include this code in your version?

**Comment by don** [comment]
This is great. Can you submit a pull request?
