### ISSUE TITLE
UID on iOS

### ISSUE THREAD

**Issue by erikm30** [chariotsolutions/phonegap-nfc#286]
According to https://github.com/hansemannn/iOS11-NFC-Example/issues/16 it should be possible to access UID and tag type also on iOS.
Would it be possible to adapt the tag object of the NFCEvent to show the id as well ?

**Comment by don** [comment]
If Apple added APIs for UID and TagType, it can be added to the plugin.

**Comment by erikm30** [comment]
There is no direct API, but according to the link above it is possible to access the data.

**Comment by scottire** [comment]
I created a pull request https://github.com/chariotsolutions/phonegap-nfc/pull/287

The interface is not public and is only gotten through `valueForKey` accessors on private instance variables which is not ideal. They should be exposed from Apple but this should do until then

**Comment by don** [comment]
@scottire I'm going to close the issue since apple rejected an app that used this (See https://github.com/chariotsolutions/phonegap-nfc/pull/287#issuecomment-340043226)
