### ISSUE TITLE
Ionic app which emulates card with share method

### ISSUE THREAD

**Issue by Vartex05** [chariotsolutions/phonegap-nfc#291]
Hi, iam trzing to building app, which will sort of emulate nfc tag or card. So user can use his mobile for example in attendace control systems and something like that. But i cant make it work. Is the share method the one which does it? Do i understand it right, that when i call share method with message that i create, the mobile will emulate card in some kind of way and the message can be read with another mobile with nfc, or with common reader? Or this must be done in some other way? Thx for answer :)

**Comment by don** [comment]
[nfc.share](https://github.com/chariotsolutions/phonegap-nfc#nfcshare) will push a NDEF message to another phone or reader.
