### ISSUE TITLE
not set clobbers

### ISSUE THREAD

**Issue by troymiao1989** [chariotsolutions/phonegap-nfc#293]
Hi,
"ReferenceError: nfc is not defined" is happened

\<js-module src="www/phonegap-nfc.js" name="NFC">
       \<clobbers target="nfc" />
\</js-module>
↑ is not included in the plugin.xml is ok? 

please help me

**Comment by don** [comment]
"ReferenceError: nfc is not defined" generally means the plugin is installed incorrectly.

Use the Cordova or PhoneGap CLI to install the plugin into your project since it copies the correct files to the proper places. Make sure you're using the latest version of the CLI.

    npm install -g cordova
    cordova create myApp com.example.myapp MyApp
    cd myApp
    cordova plugin add phonegap-nfc
