### ISSUE TITLE
Ionic iOS 4.5.0

### ISSUE THREAD

**Issue by psyfreak** [chariotsolutions/phonegap-nfc#294]
Hey I tried to use your newest version, but actually my packaging process failed:
I got the following error. 
Actually I have no clue, if this depends on your plugin...
/phonegap-nfc/NfcPlugin.h:11:9: 'CoreNFC/CoreNFC.h' file not found

**Comment by don** [comment]
It sounds like CoreNFC is missing from iOS. Make sure you're compiling with Xcode 9.
