### ISSUE TITLE
compatibility with iphone 8 / ipad

### ISSUE THREAD

**Issue by loama** [chariotsolutions/phonegap-nfc#299]
Hi, do you know if the new iphones and ipads are compatible with NFC and this plugin?

**Comment by don** [comment]
The CoreNFC docs say iPhone 7 and 7+. It *should* work on 8, 8+, and X. 

CoreNFC does not work on my iPad Pro 9.7”. Hopefully it works on newer iPads. 

https://developer.apple.com/documentation/corenfc
