### ISSUE TITLE
Truly asynchronous, stateful I/O API

### ISSUE THREAD

**Issue by mzabaluev** [chariotsolutions/phonegap-nfc#30]
The implementation of writeTag has a few problems:
- it calls blocking NFC I/O methods in the browser thread;
- it does not call close() on the tag tech object to release resources,
  as mandated by the API documentation;
- it does not lend itself well to continuous operation with multiple
  writes (and reads) in a sequence.

To solve these issues and let the client to be in control, I think a new stateful API is necessary.
My attempt at it follows the Android tag interfaces:
https://github.com/mzabaluev/phonegap-nfc/commits/async-tag-ops

The branch is commingled with other changes I've made, such as an update to Cordova 2.2. If there's interest, I can rebase the changes or just submit them sequentially (#28 would be a good start). There is no implementation for Blackberry.

**Comment by don** [comment]
Closing old issue
