### ISSUE TITLE
addTagDiscoveredListener fired twice a moment

### ISSUE THREAD

**Issue by juristamrcl** [chariotsolutions/phonegap-nfc#308]
I use reading NFC cards for sending HTTP requests. Sometimes, the addTagDiscoveredListener is fired twice at the same moment. I tryied to add the if statement immediately after firing this event, which should block doing the method, if another addTagDiscoveredListener event is fired within 1 second. But nor will it set the variable, another addTagDiscoveredListener is fired and my request is sent twice. It is also difficult to handle it in database, as it is sent almost at the same time. Using Lenovo TAB3 10 PLUS.

**Comment by KantaP** [comment]
me too

**Comment by don** [comment]
Some devices aggressively read tags. I think it's up to the app or database to handle the duplicate reads. This isn't easy to stop in Android or the plugin.

One way to handle this would be to have your event handler ignore all reads for 2 seconds after a successful read.
