### ISSUE TITLE
Foreground dispatch should only be enabled by onResume

### ISSUE THREAD

**Issue by mzabaluev** [chariotsolutions/phonegap-nfc#31]
In the current code, modifying intent filters or tech lists from JavaScript results in foreground dispatch being enabled on the NfcAdapter. These modifications may occur before onResume is called, resulting in an IllegalStateException.

Commit mzabaluev@d10fe6362d6bdfeb5e43e8b3dc154f41f56e7ee7 removes the state error.
Additionally, commit mzabaluev@98e6070d030bd9948a8e61a4b1d39c40c1f4fa8a resolves threading issues by synchronizing or context-passing the NFC dispatch and push data shared between the UI thread and the browser thread.
For your reference, the branch (based on my other changes) is posted here:
https://github.com/mzabaluev/phonegap-nfc/commits/lifecycle-fixes

**Comment by don** [comment]
Closing old issue
