### ISSUE TITLE
How to read credit card with this plugin

### ISSUE THREAD

**Issue by kapilkarda** [chariotsolutions/phonegap-nfc#311]
Is their any method, that I can read credit card data using NFC, for android and ios ?

**Comment by don** [comment]
If the credit card has a NFC tag, you might be able to read the id from the tag. The data is most likely not NDEF so you probably won't be able to read it.

Try using [NFC TagInfo by NXP](https://play.google.com/store/apps/details?id=com.nxp.taginfolite&hl=en) or [NFC TagInfo](https://play.google.com/store/apps/details?id=at.mroland.android.apps.nfctaginfo) to see if it's possible to read the card.
