### ISSUE TITLE
Error: invalid variable format: scanning when installing

### ISSUE THREAD

**Issue by jberke** [chariotsolutions/phonegap-nfc#314]
I am using VS2017 and try to install the plugin from GIT and I get this output

Installing plugin 'https://github.com/chariotsolutions/phonegap-nfc'

You have been opted out of telemetry. To change this, run: cordova telemetry on.
Error: invalid variable format: scanning
Done

**Comment by don** [comment]
This sounds like a VS2017 problem. I don't use that tool, so I'm not sure.

I recommend installing the plugin into your project from npm using the Cordova tools

    cordova plugin add phonegap-nfc

**Comment by jberke** [comment]
Yea it probably is, I did install the plugin with the CLI and its working like a champ! Nice plugin by the way

**Comment by don** [comment]
Thanks for the update. Glad it's working.
