### ISSUE TITLE
Updating NPM Link V0.7.2

### ISSUE THREAD

**Issue by Devleaf-IT** [chariotsolutions/phonegap-nfc#315]
Hi there, 

Matt here, i'm coming from the ionic forums requesting the NPM link to be updated to v0.7.2 if possible. Using the 'ionic cordova plugin add' or 'cordova plugin add' commands requires npm unless otherwise specified, so a few people are requesting the link to be updated.

[NPM Link](https://www.npmjs.com/package/phonegap-nfc)

Thanks, 

Matt

**Comment by don** [comment]
This is a problem with NPM I have a ticket open.

**Comment by Devleaf-IT** [comment]
No problem @don. Keep up the good work.

**Comment by don** [comment]
@Devleaf-IT 0.7.3 is published now. It was my fault, I was pushing to a private repo.
