### ISSUE TITLE
Problem with reading mifare classic tags 

### ISSUE THREAD

**Issue by Vartex05** [chariotsolutions/phonegap-nfc#316]
After latest Android system updates, i have problem with reading mifare classic tags with my app. There must have been some kind of changes, because exactly same mobile (Samsung Galaxy A5) read these kind of chip before the update. Now it just shows "Tag type not supported". It showed this message even before, but it was reading. Now it just shows the message, and no event is triggered, app doesnt know, that tag was read. 

I found out, that some application(NXP Tag info) can bypass this by using reader-mode API, it is mentioned in this post on stackoverflow: [https://stackoverflow.com/questions/35906081/hide-nfc-tag-type-not-supported-error-on-samsung-galaxy-devices]
Is this workaround possible with this plugin? Or some other way to read mifare classic tags in a reliable way?

**Comment by don** [comment]
Some NFC chips particularly the Broadcom ones don't support Mifare Classic. If it shows "Tag type not supported", that message is coming from Android. Currently this plugin does not have support for reader mode. See #198
