### ISSUE TITLE
iPhone's versions

### ISSUE THREAD

**Issue by VolodymyrAndrushchak** [chariotsolutions/phonegap-nfc#331]
Hey @don! 
I have one question. I see that only iPhone 7 and iPhone 7+ are supported by this plugin according to your description in docs. But what about iPhone 5s, 6, X etc?

**Comment by markus-fischbacher** [comment]
Unfortunately Apple does not support devices below iPhone 7.
That's not a restriction of phonegap-nfc itself.

**Comment by don** [comment]
@VolodymyrAndrushchak like @markus-fischbacher says Apple isn't supporting NFC on older devices, so I can't support it here.
