### ISSUE TITLE
Error Build Cordova - error: diamond operator is not supported in -source 1.6

### ISSUE THREAD

**Issue by luizalexandrew** [chariotsolutions/phonegap-nfc#332]
I'm trying to build using version 1.0.3 of the plugin and is giving this error
![captura de tela de 2018-07-04 18-40-24](https://user-images.githubusercontent.com/10445220/42294760-eff968ee-7fb9-11e8-967c-8ae7f6457b57.png)

cordova 7.1.0
android-platform 6.4.0
java version "1.8.0_171"

I downgraded to version 0.7.3 and this version is working

**Comment by VolodymyrAndrushchak** [comment]
@luizalexandrew 
Just change JAVA_VERSION on 1_8 in your gradle file

**Comment by don** [comment]
@luizalexandrew, did @VolodymyrAndrushchak 's suggestion work for you?

**Comment by Thayakaran** [comment]
@VolodymyrAndrushchak where to find gradle file in Ionic 2. 
i'm new to ionic.
Thanks in advance.

**Comment by tylervz** [comment]
@VolodymyrAndrushchak while that may be a fix for local builds, all cloud builds from a service such as Adobe PhoneGap Build will fail.

**Comment by peikezot** [comment]
Did anyone find a workaround for the cloud builds? I'm using the cloud service from Adobe's build.phonegap.com and it is indeed complaining about the diamond operators and the lambdas.

**Comment by fsobarzo** [comment]
@VolodymyrAndrushchak JAVA_VERSION on 1_8 need Jack, but this is deprecated

https://source.android.com/setup/build/jack

> Warning: As of this March 14, 2017 announcement, the Jack toolchain is deprecated. Jack was the default Android build toolchain for Android 6.0–8.1.

**Comment by sabridundar45** [comment]
https://www.youtube.com/watch?v=AQ3-i4BqOrA

**Comment by fsobarzo** [comment]
I added both parameters into `build.gradle` then do the build, but I got this error:

```
Could not find method enable() for arguments [true] on JackOptions_Decorated{isEnabled=null, isJackInProcess=null, additionalParameters=null} of type com.android.build.gradle.internal.dsl.JackOptions.
```

I have JAVA_VERSION 1_8.

**Comment by fsobarzo** [comment]
@luizalexandrew you can find a solution ?

**Comment by fredmaggiowski** [comment]
Since I couldn't upgrade Java compiler version in my cordova-based project I've had to fork the project and patch the code in order to support older java 1.6.

[Here the diff](https://github.com/chariotsolutions/phonegap-nfc/compare/master...fredmaggiowski:master).

If you're interested in the changes I could clean up the code a bit and make a pull request.

**Comment by don** [comment]
The best fix is to change the compiler to use a newer language level. Alternately you can try and older version of the plugin without the newer language features.

**Comment by adibisna** [comment]
> @luizalexandrew
> Just change JAVA_VERSION on 1_8 in your gradle file

it works for me. thanks

**Comment by KaiBirkenstock** [comment]
use this fork: https://github.com/fredmaggiowski/phonegap-nfc

**Comment by kumquat601** [comment]
@fredmaggiowski 's hack working.

at least, build successful.
