### ISSUE TITLE
ionic 3 + phonegap-nfc 1.0.3 + ios 11.4 can not work

### ISSUE THREAD

**Issue by csky89** [chariotsolutions/phonegap-nfc#333]
### android is very good, but ios 11.4 is not work, is there any demo used ionic 3?

**Comment by csky89** [comment]
My colleague took a long time to finally discover the cause of the problem.
### Now ionic-native(version 4.9.2) still does not support the nfc function of ios. You can not add "import ionic-native/nfc", only need add plugin phonegap-nfc.

Below is the code
1. in config.xml
![1531894623 1](https://user-images.githubusercontent.com/17397382/42863370-7916dd24-8a95-11e8-9533-7c0d4fa37e24.jpg)

2. 
![_20180718140958](https://user-images.githubusercontent.com/17397382/42863379-84c2699a-8a95-11e8-8f26-8b79c66171d9.png)
![_20180718141010](https://user-images.githubusercontent.com/17397382/42863385-88f7c41a-8a95-11e8-96fb-05fe98d2f5a3.png)

**Comment by acilryandi** [comment]
what about the function of tag tech? ionic-native/nfc still not support for few function like connect, close, transceive
