### ISSUE TITLE
Cannot use the plugin without ionic-native

### ISSUE THREAD

**Issue by KostasGeor** [chariotsolutions/phonegap-nfc#334]
I am trying to run the phonegap plugin without using the ionic-native. The problem is that I declare in my home.ts file variables (cordova:any, NFC:any) but none seems to work and I cannot call any function for my NFC App. What should I declare and how shall I use the plugin in order to call a function??

P.s I am using Ionic 3.

**Comment by don** [comment]
The global variable for the plugin is lowercase nfc (not NFC.)

**Comment by KostasGeor** [comment]
Thank you very much! :)

**Comment by Dehfw** [comment]
@KostasGeor 
can u provide some demo code? (import lib and use a function form phonegap-nfc)
I'm struggling at using phonegap-nfc without ionic-native too

**Comment by don** [comment]
https://github.com/chariotsolutions/phonegap-nfc#sample-projects
