### ISSUE TITLE
lambda expressions are not supported in -source 1.6

### ISSUE THREAD

**Issue by barbax** [chariotsolutions/phonegap-nfc#339]
Hello, trying to use this plugin we are receiving a strange compiling problem:
`
../platforms/android/src/com/chariotsolutions/nfc/plugin/NfcPlugin.java:800: error: lambda expressions are not supported in -source 1.6
        this.cordova.getThreadPool().execute(() -> {
                                                ^
  (use -source 8 or higher to enable lambda expressions)
`
Any idea how to solve this?

Regards

**Comment by Wade-BuildOtto** [comment]
did you solve this?

**Comment by MeMyselfI** [comment]
I just rewrote the Java 8 parts /shrug

**Comment by grimaldistudio** [comment]
I had exactly the same issue. I have Java 8 in my machines but the plugin tries to compile with the old Java 6
i manually edited build.gradle in this mode:

platform/android/build.gradle

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_6
        targetCompatibility JavaVersion.VERSION_1_6
    }

with:


compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
