### ISSUE TITLE
NDFC PUSH DISABLED

### ISSUE THREAD

**Issue by madeshv5543** [chariotsolutions/phonegap-nfc#342]
I working in nfc. I need to share data between the devices. But i can't share the message.
it show the error  NDFC_PUSH_DISABLED

**Comment by don** [comment]
You need to enable Android Beam or NFC Push in the Android settings. The exact menus depend on the phone and versions of Android, but it will be something like this.

![androidbeam](https://user-images.githubusercontent.com/3133/46684118-e40c3f00-cbbf-11e8-8332-ad5921284eb8.jpg)
![androidbeam-on](https://user-images.githubusercontent.com/3133/46684120-e66e9900-cbbf-11e8-976f-376648bfa166.png)
