### ISSUE TITLE
How to read the scanned NFC that opened the app ?

### ISSUE THREAD

**Issue by bluetiger30** [chariotsolutions/phonegap-nfc#350]
Hello,

Thanks for providing this great plugin. 

I have added the following to open the app once an NFC card is detected and it works like a charm :
```
<intent-filter>
  <action android:name="android.nfc.action.NDEF_DISCOVERED" />
  <data android:mimeType="text/pg" />
  <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
```

However, that doesn't provide me with the data of the scanned card, the only way I'm getting the data is by scanning it again after the app is opened.  so how can I make the open once it discovers an NFC card and gets its data as well without the need to scan the card again

I have a look at android developer guide and found that there is an intent that enables this but I don't know where to put it and how to use it with phone gap: EXTRA_NDEF_MESSAGES.

I'm using the following code which is an example of a NFC card reader: https://github.com/don/phonegap-nfc-reader

**Comment by don** [comment]
You need to use [nfc.addMimeTypeListener()](https://github.com/chariotsolutions/phonegap-nfc#nfcaddmimetypelistener) to get the NFC data when launching the app. You can add both a MimeTypeListener and the NDEF listener in your code. Android will call the most specific listener. Typically for a case like this I register the same function for both listeners.
