### ISSUE TITLE
Writing data to NFC tag on iOS 13

### ISSUE THREAD

**Issue by davidpadych** [chariotsolutions/phonegap-nfc#369]
Hi, are you thinking about adding the write functionality to the nfc tag for iOS 13? thanks

**Comment by TimSchue** [comment]
Yes I would like to know too, thx

**Comment by davidpadych** [comment]
Sample code: https://developer.apple.com/documentation/corenfc/creating_nfc_tags_from_your_iphone 

Sorry, i'm not a swift developer...

**Comment by davidpadych** [comment]
fork is here: https://github.com/iotize-sas/device-com-nfc.cordova

**Comment by don** [comment]
Writing NFC tags would be great. I'd like to do it eventually but I haven't looked into the details yet.

@davidpadych is that your repo? Can you send a pull request for the write functions?

**Comment by davidpadych** [comment]
Sorry.. this is not my repo

**Comment by gambarle** [comment]
I'm also very interested in being able to write to NFC tags with iOS 13 :-)

**Comment by don** [comment]
Fixed in #399 and published in phonegap-nfc v1.1.0.
