### ISSUE TITLE
Using with cordova android version 8.x.x on API SDK 28

### ISSUE THREAD

**Issue by hamzahalvanaa** [chariotsolutions/phonegap-nfc#371]
I want to use NFC plugin for my Ionic 3 project using android version 8.1.0 on API SDK 28.

Because when uploading app into the Google Play Store require the latest API SDK 28, and the NFC plugin gives me the error when installing on cordova android version 8.X.X.

It says Error: Unable to graft xml at selector "/manifest/uses-sdk" from "platforms\android\app\src\main\AndroidManifest.xml" during config install at ConfigFile_graft_child [as graft_child]

Please, someone, help me how to troubleshoot the plugin compatibility. Thank you.

**Comment by flossy** [comment]
+1

**Comment by sc0ttdav3y** [comment]
+1

I moved `<uses-sdk android:minSdkVersion="19" />` into the `<config-file target="AndroidManifest.xml" parent="/manifest">` block above and it works again.

**Comment by biswas123** [comment]
I have the same problem, I am using phonegap build. Please have a fix for this on the plugin :)

**Comment by mobidev111** [comment]
Could anyone of you open a pull request with this fix? then we can ping the maintainer to release a new version.

**Comment by LuisEGR** [comment]
Fixed here: https://github.com/chariotsolutions/phonegap-nfc/pull/372

If you need to use this fix, I uploaded it to NPM so you can use it until the issue gets merged:

`npm i phonegap-nfc-fxmanifest`

or 

`ionic cordova plugin add phonegap-nfc-fxmanifest`

**Comment by don** [comment]
#372 should fix this
