### ISSUE TITLE
How to disable Extra Authorization with NFC Share

### ISSUE THREAD

**Issue by fixdaddy** [chariotsolutions/phonegap-nfc#379]
I am very grateful to Don and contributors for making this plugin. It works beautifully reading tags.

In attempting the nfc.write method on two Android phones (Huawei P20 Pro and Samsung S5 Neo), it seems that the default Android Beam functionnality is kicking in. I am asked on both phones to touch the screen to initiate the transfer. If I do, I am asked to bring the phones back together (with a timeout of only a few seconds).

If I do all this (and it took me a dozen times to get it right), I believe the share works. The receiving phone shows that it received the data as a regular tag. The sending phone, however doesn't show the alert message I have inserted in the successful callback function... weird!

My question is : Is there a way to disable to touch screen additional action to authorize the transfer? The users running my app would already has consented to share data.

Thanks!

**Comment by don** [comment]
"Is there a way to disable to touch screen additional action to authorize the transfer?"
Unfortunately no. Early version of Android would beam without this confirmation and it worked great. Unfortunately share is clunky.
