### ISSUE TITLE
beginSession fails in iOS using ionic-native-nfc

### ISSUE THREAD

**Issue by rayron** [chariotsolutions/phonegap-nfc#381]
I have a project built in ionic 1 and angular which works on both android and ios fine.
I have since moved this over to ionic 4 using the ionic native wrapper.
Android works fine but ios is reporting an error.
"ERROR: Method 'channel:' not defined in Plugin 'NfcPlugin'.
This maybe due to the ionic native wrapper as in the docs it does not state ios as a platform.
Does anyone know of a way to access the beginSession and all nfc methods in ionic 4 without using the ionic-native wrapper?
This project is becoming a priority.

**Comment by don** [comment]
Fixed in #399 

beginSession is deprecated. Use scanNdef instead since it returns a Promise. The Ionic wrapper isn't updated yet, so use` (<any>window).nfc.scanNdef()` until it's updated.
