### ISSUE TITLE
Read out the serial number of the NFC tag (Ionic Cordova iOS13)

### ISSUE THREAD

**Issue by Patrick-89** [chariotsolutions/phonegap-nfc#390]
Hello community, 

I have a problem reading out the serial number of a n NFC Tag with iOS13 devices.

There are other native NFC reading and writing app in iOS App store which are able to read out the serial number.

But why is this not working with Ionic and Cordova?

Would be happy and thankful for information and maybe you can explain me the problem and I try to help out to solve this issue.

Thank you and Regards

**Comment by don** [comment]
Fixed in #399 and published in phonegap-nfc v1.1.0.
