### ISSUE TITLE
nfc.transceive(data) - NFC Tag write failed. Unexpected flag: 1

### ISSUE THREAD

**Issue by Lastone17** [chariotsolutions/phonegap-nfc#397]
I cant transceive some data to a NFC Device.
I can connect with nfc.connect('android.nfc.tech.NfcV')
But after that i try to send a custom Command - nfc.transceive('22 23 B6 33 3B A7 00 26 02 E0 A5 04')
I always get the Error: NFC Tag write failed. Unexpected flag: 1

With other NFC Tools from the Play Store I can send this custom command and get a Result.

What's the meaning of this error?

**Comment by don** [comment]
I have no idea what this means. I'd recommend setting a breakpoint in the Android code and looking up details based on the error.
