### ISSUE TITLE
Remove unnecessary platforms? ☠️

### ISSUE THREAD

**Issue by rodrigograca31** [chariotsolutions/phonegap-nfc#401]
* BlackBerry 10
* Windows Phone 8
* BlackBerry 7

Isn't this dead code? Who is using it? 0.00001%? 🤔

Just a thought.... if the answer is `no` please just close the issue :sweat_smile:

**Comment by don** [comment]
@rodrigograca31 you are correct those platforms are very dead. At this point It's easier to ignore them than to spend the time removing them and updating the docs etc. At some point they'll be removed.

**Comment by rodrigograca31** [comment]
Yeah I could send a PR removing them but yes lets not waste time :)
