### ISSUE TITLE
IOS : Just get UID Tag MiFare 

### ISSUE THREAD

**Issue by ymaillet91** [chariotsolutions/phonegap-nfc#403]
Hi don,
first, thank you for this plugin.
My need is to get only UID of MiFare tag.
When i scan a tag, if the memory isn"t initialized with NDEF message, an error is generate (read fail).
In the log, i see the UID but after an error is generate (read fail).
Is it possible to get only UID tag?
Thank your for your response.
Best regards
Yvan

**Comment by don** [comment]
If you see the tag id in the log, it should be returned to Javascript. Please provide more details, including which OS you're on and some example code.

**Comment by don** [comment]
This is probably the same as #416

**Comment by don** [comment]
Fixed by d34cc427e4f52fa3e25ec8aa563558c5bde04f81
