### ISSUE TITLE
Tag listeners not responding when camera preview started

### ISSUE THREAD

**Issue by bronek911** [chariotsolutions/phonegap-nfc#413]
Hi! 

I found a strange behaviour of a plugin. When the camera is not initiated everything is fine and NFC works like a charm. But in the moment that camera preview shows up, NFC listeners stops responding.

Only way of enabling it is to block, and unblock phone, while card is still attached to it. This time NFC listener successfully catches the card before the camera is reloaded(?). After that, both NFC and Camera Preview is working perfectly. Of course until the application is closed.

The most interesting part of a problem, is that it happens only on certain models. For example, there is no such problem on Xiaomi Mi9T, but on Xiaomi Mi9 there is. Also most of Huawei has same problem.

It seems like it is a problem with camera-preview but, since I'm not 100% sure I'm posting same issue here.

- [x] I searched for existing GitHub issues.
- [x] I updated all Cordova tooling to most recent version.

# Version information:

Android: 10
Cordova-android: 8.1
Devices: Xiaomi Mi9, Huawei

### Cordova-lib@9.0.1 with:
  cordova-common@3.2.1
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

### Environment: 
  OS: linux
  Node: v14.3.0
  npm: 6.14.3

### Plugins:
  Cordova-plugin-camera-preview: 0.12.0
  Phonegap-nfc: 1.1.1

**Comment by don** [comment]
IIRC when the camera loads, the app is in the background and not running. If you want to scan NFC tags while showing the camera preview I'm not sure this will work.
