### ISSUE TITLE
Compiling error NFCTagReaderSession

### ISSUE THREAD

**Issue by pmanup** [chariotsolutions/phonegap-nfc#448]
NFCTagReaderSession new -> 'new' is unavailable

after update xcode debug tool

**Comment by bartvanvelden** [comment]
[We](https://github.com/leviy/) are experiencing the same issue after the update to Xcode 12.5.

**Comment by vitgije** [comment]
Experiencing the same issue on Ionic, /Plugins/NfcPlugin.m
