### ISSUE TITLE
SerialNumber not being retrieved on iOS

### ISSUE THREAD

**Issue by PuscasAdi** [chariotsolutions/phonegap-nfc#475]
The serial number of the NFC card is not being retrieved on iOS. When I log the scanned NFC data, the `id` field is empty on iOS. On Android, it works fine. I used an `alert()` to log the NFC data, so I can attach an image with the issue
![295085038_2221389288019321_5038214624880204583_n](https://user-images.githubusercontent.com/67431791/180934097-237f7da6-0620-492d-9d40-ed97abe8d4b0.png)

**Comment by SebLevDev** [comment]
Same problem
