### ISSUE TITLE
Launching the application when a NFC tag is scanned

### ISSUE THREAD

**Issue by ikikik** [chariotsolutions/phonegap-nfc#57]
Hello guys, I just wanted to clarify something really. Now, I'm not overly knowledgeable about NFC but I know that you can use an NFC tag to open your application, right? But what I'm wondering is, could you also make that tag trigger an action within the app? So upon tapping the tag against the phone / tablet, it would open the app and trigger an event as well, such as opening a contact for example. And the contact that it would open would depend on the information in that specific tag? Is this possible? 

I would really appreciate your help! 

Thanks.

**Comment by anzrnr** [comment]
Hi Don, An extended question to this and please help me understand it better. After reading the NFC tag can it open an app+open a particular content within the app.

Ex: News App, When I tap the NFC chip, 1. It opens News app + 2. Open Sports category news.

Thanks in advance.

**Comment by sangeetjass** [comment]
As mentioned in the comment just above yours, you can simply grab the data in the tag, and based on it, you can open the category
