### ISSUE TITLE
JSON Error - when attempting to share a tag

### ISSUE THREAD

**Issue by jasonm23** [chariotsolutions/phonegap-nfc#58]
Not an Issue report, just a helpful pointer when the `JSON Error` pops up when writing or sharing a tag, it's due to the follow user error writing the method signature for `nfc.share` or `nfc.write`

```
 var record = ndef.textRecord("or any other ndef record creation method.");
 nfc.share(record,  onSuccessFunc, onFailFunc); // this will throw a JSON Error
```

The record must be in an array, ie.

```
 var record = ndef.textRecord("or any other ndef record creation method.");
 nfc.share( [ record ] ,  onSuccessFunc, onFailFunc); 
 //         ⬆       ⬆ 
```

If this was an issue report (it's a bit late since this will already be used in implementation details downstream.) it'd be a suggestion to remove the array syntax (unless multiple tags are sharable/writable at once? @don possible?)

**Comment by mobileComputingNITH** [comment]
@don @jasonm23 do you have an example of how to implement the nfc.share function? 
I have been trying to do it and it does not transfer anything. I am using ionic and angular.

Thanks in advance

**Comment by don** [comment]
@mobileComputingNITH try https://github.com/don/nfc-share

**Comment by mobileComputingNITH** [comment]
Thanks Dan for the suggestion! :)

You have done such a great job writing that plugin.
