### ISSUE TITLE
Add function to make tags readonly

### ISSUE THREAD

**Issue by don** [chariotsolutions/phonegap-nfc#6]
Ndef.makeReadOnly() and possibly NdefFormatable.formatReadOnly(message)

navigator.nfc.makeReadOnly()

// consider options object for writeTag
navigator.nfc.writeTag(ndefMessage, win, lose, { read-only: true })

**Comment by zhimeng9** [comment]
hi don, do we have an API to set password to protect the NFC tag, such as the function which is python version http://nfcpy.org/latest/modules/tag.html#nfc.tag.Tag.protect ?
